return {
    VOID = 0,

    TRAM_BIDIRECTIONAL_LEFT = 8,
    TRAM_BIDIRECTIONAL_RIGHT = 9,
    TRAM_UP = 10,
    TRAM_DOWN = 11,

    BUS_BIDIRECTIONAL_LEFT = 16,
    BUS_BIDIRECTIONAL_RIGHT = 17,
    BUS_UP_LEFT = 18,
    BUS_UP_RIGHT = 19,
    BUS_DOWN_LEFT = 20,
    BUS_DOWN_RIGHT = 21,

    TRAIN = 24,

    PLATFORM_NONE = 32,
    PLATFORM_ISLAND = 33,
    PLATFORM_LEFT = 34,
    PLATFORM_RIGHT = 35,

    ASSET = 40,

    DECORATION = 48,

    TYPE_VOID = 0,
    TYPE_TRAM = 1,
    TYPE_BUS = 2,
    TYPE_TRAIN = 3,
    TYPE_PLATFORM = 4,
    TYPE_ASSET = 5,
    TYPE_DECORATION = 6

}